cliDefaults:
  run:
    plan: false
    sequential: true
excludes:
  - '**/*.ico'
  - '**/*.png'
  - '**/*.svg'
  - docs
  - package-lock.json
imports:
  rrstack:
    - '../rrstack/.stan/system/stan.requirements.md'
    - '../rrstack/.stan/system/stan.todo.md'
    - '../rrstack/dist/react/index.d.ts'
patchOpenCommand: code -g {file}
scripts:
  typecheck: npm run typecheck
  lint: npm run lint:fix
  test: npm run test -- --no-color
  bench: npm run bench -- --no-color
  diagrams: npm run diagrams
  docs: npm run docs -- --emit none
  build: npm run build
  knip: npm run knip
stanPath: .stan
